---
cwd: <%= deploy_to %>/current
<% if mongrel_log_file %>
log_file: <%= mongrel_log_file %>
<% end %>
port: <%= mongrel_port %>
environment: <%= mongrel_environment %>
address: <%= mongrel_address %>
<% if mongrel_pid_file %>
pid_file: <%= mongrel_pid_file %>
<% end %>
servers: <%= mongrel_servers %>
<% if mongrel_user %>
user: <%= mongrel_user %>
<% end %>
<% if mongrel_group %>
group: <%= mongrel_group %>
<% end %>
